// <auto-generated />
namespace StackflowAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PostedbychangedtostringinQuestionmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PostedbychangedtostringinQuestionmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202406121542237_Posted by changed to string in Question model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
